services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_DB=vacationplanner'
      - 'POSTGRES_PASSWORD=postgres123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    command: [ 'start', '--optimized' ]
    depends_on:
      - "postgres"
    environment:
      JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.upload_scripts=enabled
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: postgres123
      KC_HEALTH_ENABLED: 'true'
      KC_HTTP_ENABLED: 'true'
      #KC_METRICS_ENABLED: 'true'
      KC_HOSTNAME_URL: http://localhost:8180
      KC_PROXY: reencrypt
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
      #- "8787:8787" # debug port

  consul-server:
    image: hashicorp/consul:latest
    command: "agent -server -bootstrap"
  consul-agent1:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
    command: "agent -join consul-server -client 0.0.0.0 -ui"
    links:
      - consul-server
    depends_on:
      - consul-server
