services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'

  consul-server:
    image: hashicorp/consul:latest
    command: "agent -server -bootstrap"
  consul-agent1:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
    command: "agent -join consul-server -client 0.0.0.0 -ui"
    links:
      - consul-server
    depends_on:
      - consul-server
